### ISSUE TITLE
Mobile controls

### ISSUE THREAD

**Issue by Victorystick** [Victorystick/shimu-hd#24]
I'd like to add a set of simple mobile controls so that mobile users can play the game. It doesn't have to be perfect, but at the very least playable.

I'm thinking of emulating a gamepad in software. A left stick for movement and a right stick for aiming, where using the right stick also fires the gun.

**Comment by zephyyrr** [comment]
I have never liked on-screen controls with mobile gaming.
I think we can do something much simpler.

Since most of the times, a player fires behind his direction of movement, how about the Mobile control just simplifies it into that. 

Hold to move and fire in opposite direction. Add some slipperiness to the control to make shimu continue moving in the same direction for a short while to allow releasing for to reload.

**Comment by Victorystick** [comment]
Fixed by #34.
